version: '3.8'
services:
  backend-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver-db:1433;databaseName=master;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Password123!
    depends_on:
      - sqlserver-db
    networks:
      - vg-network
networks:
  vg-network:
    external: true